import {randomUUID} from 'node:crypto'
import path from 'node:path'
import {readIntegrationJson,writeIntegrationJson} from '../integration-store.js'
import type {AgentTask} from '../../shared/local-ai-agent.js'
import type {WorkflowBranch,WorkflowDefinition,WorkflowDefinitionInput,WorkflowNode,WorkflowNodeRun,WorkflowRun} from '../../shared/local-ai-workflow.js'
import {LocalAgentService} from './service.js'

const now=()=>new Date().toISOString()
const text=(value:unknown,label:string,max:number,optional=false)=>{const result=String(value??'').trim();if(!result&&!optional||result.length>max)throw new Error(`${label}需要 ${optional?'0':'1'}–${max} 个字符`);return result}
const integer=(value:unknown,label:string,min:number,max:number)=>{const result=Number(value);if(!Number.isInteger(result)||result<min||result>max)throw new Error(`${label}需要 ${min}–${max} 的整数`);return result}

export class WorkflowService{
 private readonly definitionsFile:string
 private readonly versionsFile:string
 private readonly runsFile:string
 private readonly callbacks=new Map<string,(run:WorkflowRun)=>void>()
 private readonly activeAgents=new Map<string,string>()
 private readonly timeouts=new Map<string,ReturnType<typeof setTimeout>>()
 constructor(directory:string,private agent:LocalAgentService,private log?:(level:'info'|'warn'|'error',message:string)=>void,private notify?:(title:string,body:string)=>void){this.definitionsFile=path.join(directory,'definitions.json');this.versionsFile=path.join(directory,'versions.json');this.runsFile=path.join(directory,'runs.json');this.recover()}
 definitions(){const rows=readIntegrationJson<WorkflowDefinition[]>(this.definitionsFile,[]);if(!Array.isArray(rows))throw new Error('工作流定义记录已损坏');return rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
 runs(workflowId?:string,limit=100){const rows=readIntegrationJson<WorkflowRun[]>(this.runsFile,[]);if(!Array.isArray(rows))throw new Error('工作流运行记录已损坏');return rows.filter(row=>!workflowId||row.workflowId===workflowId).sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,Math.max(1,Math.min(2000,limit)))}
 private writeDefinitions(rows:WorkflowDefinition[]){writeIntegrationJson(this.definitionsFile,rows)}
 private writeRuns(rows:WorkflowRun[]){writeIntegrationJson(this.runsFile,[...rows].sort((a,b)=>a.startedAt.localeCompare(b.startedAt)).slice(-2000))}
 private node(input:WorkflowNode,ids:Set<string>):WorkflowNode{
  const name=text(input.name,'节点名称',100),legacyBranches:WorkflowBranch[]=[...(input.onSuccess?[{id:'success',name:'成功',condition:'执行成功',color:'#4a9a6e',targetNodeId:input.onSuccess}]:[]),...(input.onFailure?[{id:'failure',name:'失败',condition:'执行失败',color:'#c65a52',targetNodeId:input.onFailure}]:[])],sourceBranches=Array.isArray(input.branches)?input.branches:legacyBranches
  const branchIds=new Set<string>(),branches=sourceBranches.map((branch,index)=>{const id=text(branch.id,`节点“${name}”第 ${index+1} 条分支 ID`,80),branchName=text(branch.name,`节点“${name}”第 ${index+1} 条分支名称`,80),condition=text(branch.condition,`节点“${name}”分支“${branchName}”的判断条件`,500),color=String(branch.color||'').trim();if(branchIds.has(id))throw new Error(`节点“${name}”的分支 ID 不能重复`);branchIds.add(id);if(!/^#[0-9a-f]{6}$/i.test(color))throw new Error(`节点“${name}”分支“${branchName}”的颜色无效`);this.validateBranchCondition(condition,name,branchName);const rawTargets=Array.isArray(branch.targetNodeIds)?branch.targetNodeIds:branch.targetNodeId?[branch.targetNodeId]:[],targetNodeIds=[...new Set(rawTargets.map(target=>text(target,`节点“${name}”分支“${branchName}”的输出目标`,80)))];if(targetNodeIds.some(target=>!ids.has(target)||target===input.id))throw new Error(`节点“${name}”分支“${branchName}”的输出目标无效`);const outputValue=text(branch.outputValue,`节点“${name}”分支“${branchName}”的输出值`,4000,true);return {id,name:branchName,condition,color,...(targetNodeIds.length?{targetNodeIds}:{}),...(outputValue?{outputValue}:{})}})
  const base={id:text(input.id,'节点 ID',80),name,branches}
  if(input.type==='agent'){if(!['general','coding','documents'].includes(input.config?.mode)||!['ask','auto','full','unrestricted'].includes(input.config?.approvalMode)||!['all','any'].includes(input.config?.inputSignalMode||'all'))throw new Error(`节点“${base.name}”的 Agent 配置无效`);const inputNames=new Set<string>(),inputs=(Array.isArray(input.config.inputs)?input.config.inputs:[]).map((parameter,index)=>{const parameterName=text(parameter.name,`节点“${base.name}”第 ${index+1} 个输入参数名称`,100),value=text(parameter.value,`输入参数“${parameterName}”的值`,4000);if(inputNames.has(parameterName))throw new Error(`节点“${base.name}”的输入参数名称不能重复`);inputNames.add(parameterName);return {name:parameterName,value}});return {...base,type:'agent',config:{instruction:text(input.config.instruction,'Agent 要求',16000),model:text(input.config.model,'模型',500),mode:input.config.mode,maxSteps:integer(input.config.maxSteps,'最大步骤',1,500),fastMode:input.config.fastMode!==false,approvalMode:input.config.approvalMode,inputs,inputSignalMode:input.config.inputSignalMode||'all'}}}
  if(input.type==='condition'){const sourceNodeId=text(input.config?.sourceNodeId,'条件来源节点',80);if(!ids.has(sourceNodeId)||!['succeeded','failed'].includes(input.config?.operator))throw new Error(`节点“${base.name}”的条件配置无效`);return {...base,type:'condition',config:{sourceNodeId,operator:input.config.operator}}}
  if(input.type==='notify')return {...base,type:'notify',config:{title:text(input.config?.title,'通知标题',120),body:text(input.config?.body,'通知内容',1000)}}
  throw new Error('不支持的工作流节点类型')
 }
 private validateBranchCondition(value:string,nodeName:string,branchName:string){const condition=value.trim().toLowerCase();if(['成功','执行成功','success','succeeded','失败','执行失败','failure','failed','始终','总是','always'].includes(condition))return;if(/^(摘要|summary)\s*(包含|contains)\s*[:：]?\s*.+$/i.test(value)||/^(错误|error)\s*(包含|contains)\s*[:：]?\s*.+$/i.test(value))return;throw new Error(`节点“${nodeName}”分支“${branchName}”的判断条件无效；支持“执行成功”“执行失败”“始终”“摘要包含：文本”“错误包含：文本”`)}
 private branchMatches(branch:WorkflowBranch,success:boolean,nodeRun?:WorkflowNodeRun){const value=branch.condition.trim(),condition=value.toLowerCase();if(['成功','执行成功','success','succeeded'].includes(condition))return success;if(['失败','执行失败','failure','failed'].includes(condition))return !success;if(['始终','总是','always'].includes(condition))return true;const match=value.match(/^(摘要|summary|错误|error)\s*(包含|contains)\s*[:：]?\s*(.+)$/i);if(!match)return false;const source=/^(摘要|summary)$/i.test(match[1])?nodeRun?.summary:nodeRun?.error;return !!source?.includes(match[3].trim())}
 private validate(input:WorkflowDefinitionInput,previous?:WorkflowDefinition):WorkflowDefinition{
  if(!this.agent.projects().some(project=>project.id===input.projectId))throw new Error('请选择有效项目')
  if(!Array.isArray(input.nodes)||!input.nodes.length||input.nodes.length>100)throw new Error('工作流需要 1–100 个节点')
  const ids=new Set(input.nodes.map(node=>text(node.id,'节点 ID',80)));if(ids.size!==input.nodes.length)throw new Error('节点 ID 不能重复')
  const nodes=input.nodes.map(node=>this.node(structuredClone(node),ids)),entryNodeId=text(input.entryNodeId,'入口节点',80);if(!ids.has(entryNodeId))throw new Error('入口节点不存在')
  const map=new Map(nodes.map(node=>[node.id,node])),visiting=new Set<string>(),visited=new Set<string>()
  for(const target of nodes)if(target.type==='agent'&&target.config.inputs?.length)for(const source of nodes)for(const branch of source.branches||[])if(branch.targetNodeIds?.includes(target.id)&&!branch.outputValue)throw new Error(`节点“${source.name}”分支“${branch.name}”连接到需要输入值的 Agent“${target.name}”，必须填写输出值`)
  const targets=(node:WorkflowNode)=>node.branches?.flatMap(branch=>branch.targetNodeIds||[])||[]
  const walk=(id:string)=>{if(visiting.has(id))throw new Error('首版工作流不允许循环，请移除节点回路');if(visited.has(id))return;visiting.add(id);const node=map.get(id)!;for(const next of targets(node))walk(next);visiting.delete(id);visited.add(id)}
  walk(entryNodeId);if(visited.size!==nodes.length)throw new Error('工作流包含从入口无法到达的节点')
  const reaches=(from:string,target:string,seen=new Set<string>()):boolean=>{if(from===target)return true;if(seen.has(from))return false;seen.add(from);const node=map.get(from);return !!node&&targets(node).some(next=>reaches(next,target,seen))}
  for(const node of nodes)if(node.type==='condition'&&(node.config.sourceNodeId===node.id||!reaches(node.config.sourceNodeId,node.id)))throw new Error(`条件节点“${node.name}”只能引用此前执行的节点`)
  const layout=input.layout?.nodes&&typeof input.layout.nodes==='object'?{nodes:Object.fromEntries(nodes.flatMap(node=>{const point=input.layout!.nodes[node.id];return point&&Number.isFinite(point.x)&&Number.isFinite(point.y)?[[node.id,{x:Math.max(0,Math.min(10000,Math.round(point.x))),y:Math.max(0,Math.min(10000,Math.round(point.y)))}]]:[]})),...(input.layout.start&&Number.isFinite(input.layout.start.x)&&Number.isFinite(input.layout.start.y)?{start:{x:Math.max(0,Math.min(10000,Math.round(input.layout.start.x))),y:Math.max(0,Math.min(10000,Math.round(input.layout.start.y)))}}:{})}:undefined
  const timestamp=now();return {id:previous?.id||randomUUID(),name:text(input.name,'工作流名称',100),description:text(input.description,'工作流说明',1000,true),projectId:input.projectId,enabled:input.enabled!==false,version:(previous?.version||0)+1,entryNodeId,nodes,...(layout?{layout}:{}),timeoutMinutes:integer(input.timeoutMinutes,'工作流超时',1,1440),createdAt:previous?.createdAt||timestamp,updatedAt:timestamp}
 }
 save(input:WorkflowDefinitionInput){const rows=this.definitions(),previous=input.id?rows.find(row=>row.id===input.id):undefined;if(input.id&&!previous)throw new Error('工作流不存在');const definition=this.validate(input,previous),next=previous?rows.map(row=>row.id===definition.id?definition:row):[definition,...rows];this.writeDefinitions(next);const versions=readIntegrationJson<WorkflowDefinition[]>(this.versionsFile,[]);writeIntegrationJson(this.versionsFile,[...versions.filter(item=>item.id!==definition.id||item.version!==definition.version),definition].slice(-500));return definition}
 delete(id:string){const rows=this.definitions();if(!rows.some(row=>row.id===id))throw new Error('工作流不存在');if(this.runs(id,2000).some(run=>['running','waiting'].includes(run.status)))throw new Error('工作流正在运行，不能删除');this.writeDefinitions(rows.filter(row=>row.id!==id));this.writeRuns(this.runs(undefined,2000).filter(run=>run.workflowId!==id));const versions=readIntegrationJson<WorkflowDefinition[]>(this.versionsFile,[]);writeIntegrationJson(this.versionsFile,versions.filter(item=>item.id!==id))}
 action(id:string,action:'run'|'enable'|'pause'){const rows=this.definitions(),definition=rows.find(row=>row.id===id);if(!definition)throw new Error('工作流不存在');if(action==='run')return this.start(id);definition.enabled=action==='enable';definition.updatedAt=now();this.writeDefinitions(rows);return definition}
 start(id:string,onUpdate?:(run:WorkflowRun)=>void,startNodeId?:string,resumedFromRunId?:string){const definition=this.definitions().find(row=>row.id===id);if(!definition)throw new Error('工作流不存在');const entry=startNodeId||definition.entryNodeId;if(!definition.nodes.some(node=>node.id===entry))throw new Error('重试节点不存在');const run:WorkflowRun={id:randomUUID(),workflowId:definition.id,workflowName:definition.name,workflowVersion:definition.version,projectId:definition.projectId,status:'running',currentNodeId:entry,pendingNodeIds:[],nodeInputSignals:{},nodeRuns:[],agentTaskIds:[],startedAt:now(),...(resumedFromRunId?{resumedFromRunId}:{})};this.writeRuns([...this.runs(undefined,2000),run]);if(onUpdate)this.callbacks.set(run.id,onUpdate);const timeout=setTimeout(()=>this.fail(run.id,'工作流超过 '+definition.timeoutMinutes+' 分钟，已停止'),definition.timeoutMinutes*60_000);timeout.unref?.();this.timeouts.set(run.id,timeout);this.emit(run);void this.execute(definition,run.id,entry);return run}
 retry(runId:string,nodeId:string,onUpdate?:(run:WorkflowRun)=>void){const previous=this.runs(undefined,2000).find(run=>run.id===runId);if(!previous)throw new Error('工作流运行不存在');if(!['failed','cancelled'].includes(previous.status))throw new Error('只能从失败或取消的运行重试');if(!previous.nodeRuns.some(node=>node.nodeId===nodeId&&node.status==='failed'))throw new Error('只能从失败节点重试');return this.start(previous.workflowId,onUpdate,nodeId,previous.id)}
 cancel(runId:string){const run=this.runs(undefined,2000).find(row=>row.id===runId);if(!run)throw new Error('工作流运行不存在');if(!['running','waiting'].includes(run.status))return run;run.status='cancelled';run.finishedAt=now();run.error='用户取消了工作流';const node=[...run.nodeRuns].reverse().find(item=>item.status==='running');if(node){node.status='failed';node.error='用户取消了此节点';node.finishedAt=now()}const agentId=this.activeAgents.get(run.id);if(agentId)try{this.agent.stop(agentId,0)}catch{}this.finish(run);return run}
 private async execute(definition:WorkflowDefinition,runId:string,nodeId:string):Promise<void>{const run=this.runs(undefined,2000).find(row=>row.id===runId);if(!run||run.status!=='running')return;const node=definition.nodes.find(item=>item.id===nodeId);if(!node)return this.fail(runId,'工作流节点不存在：'+nodeId);run.currentNodeId=node.id;const nodeRun:WorkflowNodeRun={nodeId:node.id,nodeName:node.name,type:node.type,status:'running',startedAt:now()};run.nodeRuns.push(nodeRun);this.persist(run);try{
   if(node.type==='agent'){const inputs=node.config.inputs||[],values=new Map(inputs.map(item=>[item.name,item.value])),expanded=node.config.instruction.replace(/\{\{\s*([^{}]+?)\s*\}\}/g,(_match,name:string)=>values.get(name.trim())??_match),prompt=inputs.length?`${expanded}\n\n输入参数：\n${inputs.map(item=>`- ${item.name}: ${item.value}`).join('\n')}`:expanded,result=this.agent.start({projectId:definition.projectId,mode:node.config.mode,model:node.config.model,prompt,maxSteps:node.config.maxSteps,fastMode:node.config.fastMode,approvalMode:node.config.approvalMode},0,task=>this.agentUpdate(definition,run.id,node,task));nodeRun.agentTaskId=result.id;run.agentTaskIds.push(result.id);this.activeAgents.set(run.id,result.id);this.persist(run);return}
   if(node.type==='condition'){const source=run.nodeRuns.find(item=>item.nodeId===node.config.sourceNodeId),matched=source?.status===node.config.operator;nodeRun.status='succeeded';nodeRun.summary=matched?'条件成立':'条件不成立';nodeRun.finishedAt=now();this.persist(run);return this.advance(definition,run,node,matched)}
   this.notify?.(node.config.title,node.config.body);nodeRun.status='succeeded';nodeRun.summary='通知已发送';nodeRun.finishedAt=now();this.persist(run);return this.advance(definition,run,node,true)
  }catch(error){nodeRun.status='failed';nodeRun.error=String(error);nodeRun.finishedAt=now();this.persist(run);return this.advance(definition,run,node,false)}
 }
 private agentUpdate(definition:WorkflowDefinition,runId:string,node:WorkflowNode,task:AgentTask){if(['running','waiting'].includes(task.status))return;const run=this.runs(undefined,2000).find(row=>row.id===runId);if(!run||run.status!=='running')return;this.activeAgents.delete(runId);const nodeRun=[...run.nodeRuns].reverse().find(item=>item.nodeId===node.id&&item.status==='running');if(!nodeRun)return;const success=task.status==='completed';nodeRun.status=success?'succeeded':'failed';nodeRun.error=task.error||undefined;nodeRun.summary=[...task.events].reverse().find(event=>event.kind==='assistant'&&event.text&&!event.text.startsWith('本次模型未调用工具'))?.text.slice(0,2000);nodeRun.finishedAt=now();this.persist(run);void this.advance(definition,run,node,success)}
 private incomingSources(definition:WorkflowDefinition,nodeId:string){return [...new Set(definition.nodes.filter(source=>source.branches?.some(branch=>branch.targetNodeIds?.includes(nodeId))).map(source=>source.id))]}
 private inputReady(definition:WorkflowDefinition,run:WorkflowRun,node:WorkflowNode){if(node.type!=='agent'||node.config.inputSignalMode==='any')return true;const expected=this.incomingSources(definition,node.id);if(expected.length<2)return true;const received=new Set(run.nodeInputSignals?.[node.id]||[]);return expected.every(source=>received.has(source))}
 private continueRun(definition:WorkflowDefinition,run:WorkflowRun){while(run.pendingNodeIds?.length){const next=run.pendingNodeIds.shift()!;if(run.nodeRuns.some(item=>item.nodeId===next))continue;this.persist(run);return this.execute(definition,run.id,next)}const waiting=definition.nodes.find(node=>node.type==='agent'&&!run.nodeRuns.some(item=>item.nodeId===node.id)&&(run.nodeInputSignals?.[node.id]?.length||0)>0&&!this.inputReady(definition,run,node));if(waiting){const received=new Set(run.nodeInputSignals?.[waiting.id]||[]),missing=this.incomingSources(definition,waiting.id).filter(source=>!received.has(source)).map(id=>definition.nodes.find(node=>node.id===id)?.name||id);return this.fail(run.id,`Agent“${waiting.name}”正在等待全部执行输入，缺少：${missing.join('、')}`)}run.status='succeeded';run.finishedAt=now();run.currentNodeId=undefined;run.summary=[...run.nodeRuns].reverse().find(item=>item.outputValue||item.summary)?.outputValue||[...run.nodeRuns].reverse().find(item=>item.summary)?.summary||'工作流执行完成';this.finish(run)}
 private async advance(definition:WorkflowDefinition,run:WorkflowRun,node:WorkflowNode,success:boolean){if(run.status!=='running')return;const nodeRun=run.nodeRuns.at(-1),branch=node.branches?.find(item=>this.branchMatches(item,success,nodeRun));if(branch&&nodeRun){nodeRun.branchId=branch.id;nodeRun.branchName=branch.name;if(branch.outputValue){nodeRun.outputValue=branch.outputValue;nodeRun.summary=branch.outputValue}const queued=new Set([...(run.pendingNodeIds||[]),...run.nodeRuns.map(item=>item.nodeId)]);run.pendingNodeIds=run.pendingNodeIds||[];run.nodeInputSignals=run.nodeInputSignals||{};for(const targetId of branch.targetNodeIds||[]){const signals=run.nodeInputSignals[targetId]||[];if(!signals.includes(node.id))signals.push(node.id);run.nodeInputSignals[targetId]=signals;const target=definition.nodes.find(item=>item.id===targetId);if(target&&this.inputReady(definition,run,target)&&!queued.has(targetId)){run.pendingNodeIds.push(targetId);queued.add(targetId)}}this.persist(run)}if(node.branches?.length&&!branch)return this.fail(run.id,`节点“${node.name}”没有命中任何分支`);if(!success&&!branch)return this.fail(run.id,nodeRun?.error||`节点“${node.name}”执行失败`);return this.continueRun(definition,run)}
 private fail(runId:string,error:string){const run=this.runs(undefined,2000).find(row=>row.id===runId);if(!run||!['running','waiting'].includes(run.status))return;run.status='failed';run.error=error;run.finishedAt=now();const node=[...run.nodeRuns].reverse().find(item=>item.status==='running');if(node){node.status='failed';node.error=error;node.finishedAt=now()}const agentId=this.activeAgents.get(run.id);if(agentId)try{this.agent.stop(agentId,0)}catch{}this.finish(run)}
 private persist(run:WorkflowRun){const rows=this.runs(undefined,2000);const index=rows.findIndex(row=>row.id===run.id);if(index>=0)rows[index]=run;else rows.push(run);this.writeRuns(rows);this.emit(run)}
 private finish(run:WorkflowRun){const timeout=this.timeouts.get(run.id);if(timeout)clearTimeout(timeout);this.timeouts.delete(run.id);this.activeAgents.delete(run.id);this.persist(run);this.log?.(run.status==='succeeded'?'info':'warn',`工作流“${run.workflowName}”${run.status==='succeeded'?'执行成功':run.status==='cancelled'?'已取消':'执行失败'}${run.error?'；'+run.error:''}`);this.callbacks.delete(run.id)}
 private emit(run:WorkflowRun){this.callbacks.get(run.id)?.(structuredClone(run))}
 private recover(){const rows=this.runs(undefined,2000);let changed=false;for(const run of rows)if(['running','waiting'].includes(run.status)){run.status='failed';run.error='应用在执行期间关闭，结果未确认；不会自动重放。';run.finishedAt=now();changed=true}if(changed)this.writeRuns(rows)}
 dispose(){for(const run of this.runs(undefined,2000).filter(row=>['running','waiting'].includes(row.status)))this.cancel(run.id);for(const timeout of this.timeouts.values())clearTimeout(timeout);this.timeouts.clear();this.callbacks.clear()}
}
