<script setup lang="ts">
import {ref,watch} from 'vue'
import type {AgentProject,AgentPolicy} from '../../electron/shared/local-ai-agent'
const props=defineProps<{project:AgentProject;disabled:boolean}>()
const emit=defineEmits<{updated:[project:AgentProject]}>()
const policy=ref<AgentPolicy>('confirm'),paths=ref(''),memory=ref(''),busy=ref(false),error=ref('')
watch(()=>props.project,value=>{policy.value=value.policy||'confirm';paths.value=(value.autoWritePaths||[]).join('\n');memory.value=value.memory||''},{immediate:true})
async function save(){busy.value=true;error.value='';try{emit('updated',await window.myplane.localAiStudio('agentUpdateProject',{id:props.project.id,policy:policy.value,autoWritePaths:paths.value.split('\n').map(item=>item.trim()).filter(Boolean),memory:memory.value}))}catch(e){error.value=String(e)}finally{busy.value=false}}
</script>
<template><details class="project-settings"><summary aria-label="项目权限与记忆">{{project.policy==='read-only'?'只读分析':project.policy==='project-auto'?'项目自动修改':'确认执行'}}</summary><div class="project-settings-panel"><strong>项目权限与记忆</strong><label>执行策略<select v-model="policy" :disabled="disabled||busy"><option value="read-only">只读分析</option><option value="confirm">确认执行（默认）</option><option value="project-auto">项目自动修改</option></select></label><label v-if="policy==='project-auto'">允许自动修改的相对目录<textarea v-model="paths" rows="2" placeholder="例如 src，每行一个目录" :disabled="disabled||busy"/></label><label>项目记忆<textarea v-model="memory" rows="4" maxlength="6000" placeholder="项目约定、关键决策或待办；作为参考，不代替验证。" :disabled="disabled||busy"/></label><p>当前终端未隔离。命令、测试脚本和外部工具仍需确认。</p><p v-if="error" role="alert">{{error}}</p><button :disabled="disabled||busy" @click="save">{{busy?'保存中…':'保存项目设置'}}</button></div></details></template>
<style scoped>.project-settings{position:relative;font-size:11px;color:var(--s-dim);flex:none}.project-settings summary{cursor:pointer;list-style:none;padding:5px 8px;border:1px solid var(--s-border);border-radius:7px}.project-settings-panel{position:absolute;right:0;top:35px;width:280px;max-height:65vh;overflow:auto;padding:16px;z-index:20;background:var(--s-panel);border:1px solid var(--s-border);border-radius:10px;box-shadow:0 8px 25px #0002;color:var(--s-text)}label{display:flex;flex-direction:column;gap:5px;margin:12px 0}textarea,select,button{font:inherit;color:inherit;background:var(--s-panel);border:1px solid var(--s-border);border-radius:6px;padding:7px;max-width:100%;box-sizing:border-box}p{line-height:1.7;color:var(--s-dim)}button{cursor:pointer;width:100%}@container studio (max-width:580px){.project-settings-panel{position:fixed;right:12px;top:80px}}</style>
