<script setup lang="ts">
import {CopyDocument} from '@element-plus/icons-vue'
import {ElMessage} from 'element-plus'

type ValidationItem={id:string;title:string;kind:string;state:string;status:string;summary:string;exitCode?:number;duration?:number;command:string;parameters:string;raw:string}
type ValidationDetail={title:string;kind:string;state:string;status:string;summary:string;exitCode?:number;duration?:number;count:number;items:ValidationItem[]}
const props=defineProps<{detail:ValidationDetail;expanded?:boolean}>()
const emit=defineEmits<{close:[];toggleExpand:[]}>()
async function copy(){
 const value=props.detail.items.map((item,index)=>[props.detail.count>1?`第 ${index+1} 项`:'',item.command?`执行命令\n${item.command}`:item.parameters?`执行参数\n${item.parameters}`:'',`原始输出\n${item.raw||'无输出'}`].filter(Boolean).join('\n\n')).join('\n\n----------------\n\n')
 try{await navigator.clipboard.writeText(value);ElMessage.success('已复制验证详情')}catch(error){ElMessage.error(String(error))}
}
</script>

<template>
 <aside class="validation-detail-pane" :class="{expanded}" role="region" :aria-label="`${detail.title}验证详情`">
  <header><div><strong>{{detail.title}}</strong><span>{{detail.kind}}<template v-if="detail.count>1"> · {{detail.count}} 项</template></span></div><button title="复制详情" aria-label="复制验证详情" @click="copy"><CopyDocument/></button><button :title="expanded?'缩小到右侧':'展开详情区域'" :aria-label="expanded?'缩小到右侧':'展开详情区域'" @click="emit('toggleExpand')"><svg v-if="!expanded" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4H4v5M15 20h5v-5M4 4l6 6m10 10-6-6"/></svg><svg v-else viewBox="0 0 24 24" aria-hidden="true"><path d="M10 10H5V5m9 9h5v5M5 10l5-5m9 9-5 5"/></svg></button><button class="panel-toggle" title="关闭详情" aria-label="关闭验证详情" @click="emit('close')"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg></button></header>
  <div class="validation-detail-body">
   <section class="validation-detail-summary"><span class="validation-detail-status" :class="detail.state">{{detail.status}}</span><div><strong>{{detail.summary}}</strong><small><template v-if="detail.exitCode!==undefined">退出码 {{detail.exitCode}}</template><template v-if="detail.duration!==undefined"> · 用时 {{(detail.duration/1000).toFixed(1)}} 秒</template></small></div></section>
   <article v-for="(item,index) in detail.items" :key="item.id" class="validation-detail-item"><header v-if="detail.count>1"><strong>第 {{index+1}} 项</strong><span>{{item.duration===undefined?'未记录耗时':(item.duration/1000).toFixed(1)+' 秒'}}<template v-if="item.exitCode!==undefined"> · 退出码 {{item.exitCode}}</template></span></header><section v-if="item.command||item.parameters"><h3>{{item.command?'执行命令':'执行参数'}}</h3><pre>{{item.command||item.parameters}}</pre></section><section><h3>原始输出</h3><pre>{{item.raw||'无输出'}}</pre></section></article>
  </div>
 </aside>
</template>

<style scoped>
.validation-detail-pane{display:flex;flex:none;flex-direction:column;width:clamp(420px,46%,760px);min-width:0;height:100%;overflow:hidden;border-left:1px solid #29352f;background:#101713;color:#dce8e0}.validation-detail-pane.expanded{flex:1;width:auto}.validation-detail-pane>header{display:flex;align-items:center;gap:5px;min-height:52px;padding:8px 10px 8px 16px;border-bottom:1px solid #29352f;background:#151e19}.validation-detail-pane>header>div{display:flex;align-items:baseline;gap:10px;min-width:0;flex:1}.validation-detail-pane>header strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.validation-detail-pane>header span{color:#82958a;font:11px Consolas,monospace}.validation-detail-pane button{display:grid;place-items:center;width:32px;height:32px;padding:7px;border:0;border-radius:8px;background:transparent;color:#a9b9b0}.validation-detail-pane button:hover{background:#233029;color:#fff}.validation-detail-pane button svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.validation-detail-pane .panel-toggle{background:#202923;color:#e3ebe6}.validation-detail-body{flex:1;min-height:0;overflow:auto;padding:18px}.validation-detail-body>section{margin-bottom:20px}.validation-detail-summary{display:flex;align-items:flex-start;gap:11px;padding:13px;border:1px solid #29352f;border-radius:9px;background:#151e19}.validation-detail-summary>div{display:flex;flex-direction:column;gap:4px;min-width:0}.validation-detail-summary strong{font-size:12px;line-height:1.65}.validation-detail-summary small{color:#82958a;font-size:11px}.validation-detail-status{flex:none;padding:3px 8px;border-radius:999px;background:#26312b;color:#a9b9b0;font-size:10px;font-weight:650}.validation-detail-status.passed{background:#20392b;color:#8fd1a7}.validation-detail-status.failed{background:#3c2424;color:#ee9999}.validation-detail-item{padding:0 0 18px;margin:0 0 18px;border-bottom:1px solid #29352f}.validation-detail-item:last-child{margin-bottom:0;border-bottom:0}.validation-detail-item>header{display:flex;align-items:center;justify-content:space-between;margin:0 0 12px}.validation-detail-item>header strong{font-size:12px}.validation-detail-item>header span{color:#82958a;font-size:10px}.validation-detail-item>section+section{margin-top:15px}.validation-detail-body h3{margin:0 0 8px;color:#82958a;font-size:11px;font-weight:600}.validation-detail-body pre{max-height:50vh;overflow:auto;margin:0;padding:12px;border:1px solid #29352f;border-radius:8px;background:#0d1410;color:#cdd8d1;white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.7 'SFMono-Regular',Consolas,'Microsoft YaHei UI',monospace}@container studio (max-width:1000px){.validation-detail-pane{width:50%;min-width:340px}}@container studio (max-width:700px){.validation-detail-pane{position:absolute;inset:0 0 0 auto;z-index:30;width:100%;min-width:0}.validation-detail-pane.expanded{width:100%}}
</style>
