<script setup lang="ts">
import {onMounted,ref} from 'vue'
import type {AgentProject} from '../../electron/shared/local-ai-agent'
import type {McpServerView,McpServerInput} from '../../electron/shared/local-ai-mcp'
const servers=ref<McpServerView[]>([]),projects=ref<AgentProject[]>([]),busy=ref(false),error=ref(''),notice=ref('')
const name=ref(''),projectId=ref(''),transport=ref<'stdio'|'http'>('stdio'),command=ref(''),args=ref('[]'),env=ref(''),url=ref(''),token=ref(''),protocol=ref<'legacy'|'modern'>('legacy')
async function refresh(){[servers.value,projects.value]=await Promise.all([window.myplane.localAiStudio('mcpServers'),window.myplane.localAiStudio('agentProjects')]);if(!projectId.value)projectId.value=projects.value[0]?.id||''}
async function run(work:()=>Promise<void>){busy.value=true;error.value='';try{await work();await refresh()}catch(e){error.value=String(e)}finally{busy.value=false}}
async function add(){await run(async()=>{await window.myplane.localAiStudio('mcpSave',{name:name.value,projectId:projectId.value,transport:transport.value,command:command.value,args:JSON.parse(args.value),url:url.value,protocol:protocol.value,...(env.value.trim()?{env:JSON.parse(env.value)}:{}),...(token.value?{token:token.value}:{}),enabledTools:[]});name.value='';env.value='';token.value='';notice.value='已保存，连接后选择需要的工具。'})}
async function connect(item:McpServerView){await run(async()=>{await window.myplane.localAiStudio('mcpConnect',{id:item.id})})}
async function grant(item:McpServerView){await run(async()=>{const input:McpServerInput={id:item.id,name:item.name,projectId:item.projectId,transport:item.transport,command:item.command,args:item.args,url:item.url,protocol:item.protocol,enabledTools:item.tools.filter(tool=>tool.enabled).map(tool=>tool.name)};await window.myplane.localAiStudio('mcpSave',JSON.parse(JSON.stringify(input)));notice.value='工具权限已保存，下一次发送任务时生效。'})}
onMounted(()=>run(refresh))
</script>
<template><section class="agent-extensions"><header><h3>MCP 外部工具</h3><button :disabled="busy" @click="run(refresh)">刷新状态</button></header><p>按项目连接工具服务。工具调用逐次确认，服务进程未被系统沙箱隔离。</p><p v-if="error" role="alert" class="error">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><article v-for="item in servers" :key="item.id"><header><strong>{{item.name}}</strong><span>{{item.status==='connected'?'已连接':item.status==='connecting'?'连接中':item.status==='error'?'连接失败':'未连接'}}</span></header><small>{{projects.find(project=>project.id===item.projectId)?.name}} · {{item.transport==='stdio'?item.command:item.url}}</small><p v-if="item.error" class="error">{{item.error}}</p><p v-if="item.identity">服务身份：{{item.identity}}</p><div class="actions"><button v-if="item.status!=='connected'" :disabled="busy" @click="connect(item)">连接 / 重新发现</button><button v-else :disabled="busy" @click="run(async()=>{await window.myplane.localAiStudio('mcpDisconnect',{id:item.id})})">断开</button><button :disabled="busy" @click="run(async()=>{await window.myplane.localAiStudio('mcpDelete',{id:item.id})})">移除连接</button></div><details v-if="item.tools.length"><summary>选择允许使用的工具（最多 20 个）</summary><label v-for="tool in item.tools" :key="tool.name" class="tool-option"><input v-model="tool.enabled" type="checkbox" :disabled="busy"/><span><strong>{{tool.name}}</strong><small>{{tool.description}}</small></span></label><button :disabled="busy" @click="grant(item)">保存工具权限</button></details></article><details class="mcp-add"><summary>添加 MCP 服务</summary><div class="form-grid"><label>名称<input v-model="name" maxlength="80" placeholder="服务名称"/></label><label>关联项目<select v-model="projectId"><option v-for="project in projects" :key="project.id" :value="project.id">{{project.name}}</option></select></label><label>连接方式<select v-model="transport"><option value="stdio">本机程序（stdio）</option><option value="http">远程服务（Streamable HTTP）</option></select></label><label>协议<select v-model="protocol"><option value="legacy">2025 兼容协议</option><option value="modern">2026-07-28</option></select></label><template v-if="transport==='stdio'"><label class="wide">程序绝对路径<input v-model="command" placeholder="/绝对路径/已安装的程序"/></label><label class="wide">启动参数（JSON 数组）<textarea v-model="args" rows="2"/></label><label class="wide">显式环境变量（JSON，安全存储）<textarea v-model="env" rows="2" placeholder='{"NAME":"value"}'/></label></template><template v-else><label class="wide">服务地址<input v-model="url" placeholder="https://example.com/mcp"/></label><label class="wide">Bearer Token（可选，安全存储）<input v-model="token" type="password" autocomplete="new-password"/></label></template></div><p v-if="!projects.length">请先在工作台创建项目。</p><button :disabled="busy||!name.trim()||!projectId" @click="add">保存连接</button></details></section></template>
<style scoped>.agent-extensions{border:1px solid var(--s-border);border-radius:12px;padding:20px;margin-top:20px;font-size:13px;color:var(--s-text);background:var(--s-panel)}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h3{margin:0;font-size:15px}p,small{color:var(--s-dim);line-height:1.7;overflow-wrap:anywhere}.error{color:var(--s-danger)}article{padding:16px 0;border-bottom:1px solid var(--s-border)}button,input,select,textarea{font:inherit;color:inherit;background:var(--s-panel);border:1px solid var(--s-border);border-radius:7px;padding:8px;min-width:0;box-sizing:border-box}button,summary{cursor:pointer}button:disabled{opacity:.5}.actions{display:flex;gap:8px;margin:12px 0}details{margin-top:16px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}label{display:flex;flex-direction:column;gap:6px}.wide{grid-column:1/-1}.tool-option{flex-direction:row;margin:12px 0}.tool-option small{display:block}.tool-option input{align-self:flex-start}.mcp-add{padding-top:10px}@container studio (max-width:700px){.form-grid{grid-template-columns:1fr}}
</style>
