<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {AlarmClock,Delete,Edit,Plus,RefreshRight,VideoPause,VideoPlay} from '@element-plus/icons-vue'
import type {AgentProject} from '../../electron/shared/local-ai-agent'
import type {AutomationRun,AutomationTask,AutomationTaskInput,AutomationTemplate} from '../../electron/shared/local-ai-automation'
import type {StudioServerModel} from '../../electron/shared/local-ai-studio'
import type {WorkflowDefinition} from '../../electron/shared/local-ai-workflow'

const props=defineProps<{model:string;models:StudioServerModel[]}>()
const api=window.myplane.localAiStudio
const tasks=ref<AutomationTask[]>([]),runs=ref<AutomationRun[]>([]),projects=ref<AgentProject[]>([]),templates=ref<AutomationTemplate[]>([]),workflows=ref<WorkflowDefinition[]>([])
const selectedId=ref(''),editing=ref(false),busy=ref(''),error=ref(''),historyTask=ref('')
const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai'
const fresh=()=>({id:'',name:'',projectId:'',instruction:'',targetType:'agent',workflowId:'',templateId:'',templateParameters:{} as Record<string,unknown>,enabled:true,triggerType:'daily',onceAt:'',intervalMinutes:60,time:'09:00',weekdays:[1,2,3,4,5] as number[],cron:'0 9 * * 1-5',timezone,model:props.model||'',mode:'coding',maxSteps:30,fastMode:true,approvalMode:'ask',timeoutMinutes:60,retryMax:1,retryDelayMinutes:10,notifyOn:'failure'})
const form=reactive(fresh())
let timer:ReturnType<typeof setInterval>|undefined
const selected=computed(()=>tasks.value.find(item=>item.id===selectedId.value))
const visibleRuns=computed(()=>runs.value.filter(item=>!historyTask.value||item.taskId===historyTask.value))
const activeCount=computed(()=>tasks.value.filter(item=>item.enabled).length)
const runningCount=computed(()=>runs.value.filter(item=>['queued','running','retry-wait'].includes(item.status)).length)
const template=computed(()=>templates.value.find(item=>item.id===form.templateId))
const templateProperties=computed(()=>Object.entries((template.value?.parameterSchema?.properties||{}) as Record<string,{title?:string;type?:string}>))
const projectWorkflows=computed(()=>workflows.value.filter(item=>item.enabled&&item.projectId===form.projectId))
const projectName=(id:string)=>projects.value.find(item=>item.id===id)?.name||'项目已移除'
const date=(value?:string)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'
const statusLabel=(value?:AutomationRun['status'])=>value?({queued:'排队中',running:'执行中','retry-wait':'等待重试',succeeded:'成功',failed:'失败',cancelled:'已取消',skipped:'已跳过'} satisfies Record<AutomationRun['status'],string>)[value]:'尚未运行'
const triggerLabel=(item:AutomationTask)=>item.trigger.type==='once'?`单次 · ${date(item.trigger.at)}`:item.trigger.type==='interval'?`每 ${item.trigger.minutes} 分钟`:item.trigger.type==='daily'?`每天 ${item.trigger.time}`:item.trigger.type==='weekly'?`每周 ${item.trigger.weekdays.map(day=>'日一二三四五六'[day]).join('、')} ${item.trigger.time}`:`Cron · ${item.trigger.expression}`
function localDateTime(value:string){const date=new Date(value),offset=date.getTimezoneOffset();return Number.isNaN(date.getTime())?'':new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}
async function load(){try{const [nextTasks,nextRuns,nextProjects,nextTemplates,nextWorkflows]=await Promise.all([api('automationTasks'),api('automationRuns',{limit:200}),api('agentProjects'),api('automationTemplates'),api('workflowDefinitions')]);tasks.value=nextTasks;runs.value=nextRuns;projects.value=nextProjects;templates.value=nextTemplates;workflows.value=nextWorkflows;if(selectedId.value&&!nextTasks.some(item=>item.id===selectedId.value))selectedId.value=''}catch(cause){error.value=String(cause).replace(/^Error: /,'')}}
function create(){Object.assign(form,fresh(),{projectId:projects.value[0]?.id||'',model:props.model||props.models[0]?.id||''});editing.value=true;selectedId.value=''}
function edit(item:AutomationTask){const trigger=item.trigger;Object.assign(form,{...fresh(),id:item.id,name:item.name,projectId:item.projectId,instruction:item.instruction,targetType:item.workflowId?'workflow':'agent',workflowId:item.workflowId||'',templateId:item.templateId||'',templateParameters:{...(item.templateParameters||{})},enabled:item.enabled,triggerType:trigger.type,onceAt:trigger.type==='once'?localDateTime(trigger.at):'',intervalMinutes:trigger.type==='interval'?trigger.minutes:60,time:trigger.type==='daily'||trigger.type==='weekly'?trigger.time:'09:00',weekdays:trigger.type==='weekly'?[...trigger.weekdays]:[1,2,3,4,5],cron:trigger.type==='cron'?trigger.expression:'0 9 * * 1-5',timezone:item.timezone,model:item.agent.model,mode:item.agent.mode,maxSteps:item.agent.maxSteps,fastMode:item.agent.fastMode,approvalMode:item.agent.approvalMode,timeoutMinutes:item.execution.timeoutMinutes,retryMax:item.execution.retryMax,retryDelayMinutes:item.execution.retryDelayMinutes,notifyOn:item.output.notifyOn});selectedId.value=item.id;editing.value=true}
function applyTemplate(){const item=template.value;if(!item)return;form.name=item.name;form.instruction=item.instruction;form.mode=item.mode;form.approvalMode=item.approvalMode;form.templateParameters={}}
function payload():AutomationTaskInput{const trigger=form.triggerType==='once'?{type:'once' as const,at:new Date(form.onceAt).toISOString()}:form.triggerType==='interval'?{type:'interval' as const,minutes:Number(form.intervalMinutes)}:form.triggerType==='daily'?{type:'daily' as const,time:form.time}:form.triggerType==='weekly'?{type:'weekly' as const,time:form.time,weekdays:[...form.weekdays]}:{type:'cron' as const,expression:form.cron};return {...(form.id?{id:form.id}:{}),name:form.name,enabled:form.enabled,projectId:form.projectId,instruction:form.targetType==='workflow'?'工作流触发':form.instruction,trigger,timezone:form.timezone,agent:{model:form.model,mode:form.mode as 'coding'|'documents'|'general',maxSteps:Number(form.maxSteps),fastMode:form.fastMode,approvalMode:form.approvalMode as 'ask'|'auto'|'full'|'unrestricted'},execution:{timeoutMinutes:Number(form.timeoutMinutes),retryMax:Number(form.retryMax),retryDelayMinutes:Number(form.retryDelayMinutes),concurrency:'forbid'},output:{notifyOn:form.notifyOn as 'always'|'failure'|'never'},...(form.targetType==='workflow'?{workflowId:form.workflowId}:form.templateId?{templateId:form.templateId,templateParameters:{...form.templateParameters}}:{})}}
async function save(){busy.value='save';error.value='';try{const item=await api('automationSave',payload());await load();selectedId.value=item.id;editing.value=false;ElMessage.success('定时任务已保存')}catch(cause){error.value=String(cause).replace(/^Error: /,'')}finally{busy.value=''}}
async function action(item:AutomationTask,value:'enable'|'pause'|'run'){busy.value=item.id+value;try{await api('automationAction',{id:item.id,action:value});await load();if(value==='run')ElMessage.success('已创建一次独立运行')}catch(cause){ElMessage.error(String(cause))}finally{busy.value=''}}
async function remove(item:AutomationTask){try{await ElMessageBox.confirm(`删除“${item.name}”及其运行历史？`,'删除定时任务',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await api('automationDelete',{id:item.id});await load()}catch(cause){if(cause!=='cancel'&&cause!=='close')ElMessage.error(String(cause))}}
function showHistory(item?:AutomationTask){historyTask.value=item?.id||'';editing.value=false;if(item)selectedId.value=item.id}
watch(()=>props.model,value=>{if(!form.model)form.model=value})
onMounted(()=>{void load();timer=setInterval(()=>void load(),5000)})
onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>

<template>
 <main class="automation-page scroll-page">
  <header class="automation-header"><div><span class="eyebrow">AUTOMATIONS</span><h1>定时任务</h1><p>按计划唤醒 Agent，每次创建独立运行并保留结果。应用需在后台运行。</p></div><button class="primary-button" :disabled="!projects.length" @click="create"><Plus/>新建任务</button></header>
  <div v-if="error" class="automation-error">{{error}}<button @click="error=''">关闭</button></div>
  <section class="automation-stats"><div><strong>{{tasks.length}}</strong><span>全部任务</span></div><div><strong>{{activeCount}}</strong><span>已启用</span></div><div><strong>{{runningCount}}</strong><span>执行中 / 重试</span></div></section>
  <div v-if="!projects.length" class="automation-empty"><AlarmClock/><h3>先创建一个 Agent 项目</h3><p>定时任务需要固定项目目录和项目权限，创建后再回到这里配置。</p></div>
  <div v-else class="automation-grid">
   <section class="automation-list"><header><h2>任务</h2><button class="icon-btn" title="刷新" @click="load"><RefreshRight/></button></header><div v-if="!tasks.length" class="automation-empty compact"><AlarmClock/><p>还没有定时任务</p></div>
    <article v-for="item in tasks" :key="item.id" class="automation-card" :class="{selected:selectedId===item.id}" @click="selectedId=item.id;editing=false"><div class="automation-card-top"><span class="automation-toggle" :class="{enabled:item.enabled}"><i></i>{{item.enabled?'已启用':'已暂停'}}</span><span class="run-state" :class="item.state.lastStatus">{{statusLabel(item.state.lastStatus)}}</span></div><h3>{{item.name}}</h3><p>{{triggerLabel(item)}} · {{item.timezone}}</p><small>{{projectName(item.projectId)}} · 下次 {{date(item.state.nextRunAt)}}</small><div class="automation-actions"><button title="立即运行" :disabled="!!busy" @click.stop="action(item,'run')"><VideoPlay/>运行</button><button :disabled="!!busy" @click.stop="action(item,item.enabled?'pause':'enable')"><component :is="item.enabled?VideoPause:VideoPlay"/>{{item.enabled?'暂停':'启用'}}</button><button title="编辑" @click.stop="edit(item)"><Edit/></button><button title="运行历史" @click.stop="showHistory(item)">历史</button><button class="danger" title="删除" @click.stop="remove(item)"><Delete/></button></div></article>
   </section>
   <section class="automation-detail">
    <form v-if="editing" class="automation-form" @submit.prevent="save"><header><div><span class="eyebrow">{{form.id?'EDIT':'NEW'}}</span><h2>{{form.id?'编辑任务':'新建任务'}}</h2></div><button type="button" class="text-button" @click="editing=false">取消</button></header>
     <div class="form-grid"><label>执行目标<select v-model="form.targetType"><option value="agent">单个 Agent</option><option value="workflow">工作流</option></select></label><label>名称<input v-model="form.name" maxlength="100" required/></label><label>项目<select v-model="form.projectId" required @change="form.workflowId=''"><option v-for="item in projects" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label v-if="form.targetType==='workflow'">工作流<select v-model="form.workflowId" required><option value="" disabled>选择已启用工作流</option><option v-for="item in projectWorkflows" :key="item.id" :value="item.id">{{item.name}} · v{{item.version}}</option></select></label><label v-if="form.targetType==='agent'" class="wide">任务模板<select v-model="form.templateId" @change="applyTemplate"><option value="">自定义</option><option v-for="item in templates" :key="item.id" :value="item.id">{{item.name}} — {{item.description}}</option></select></label><label v-if="form.targetType==='agent'" class="wide">任务要求<textarea v-model="form.instruction" rows="5" maxlength="16000" required></textarea></label>
      <label v-for="([key,schema]) in (form.targetType==='agent'?templateProperties:[])" :key="key">{{schema.title||key}}<input v-model="form.templateParameters[key]"/></label>
      <label>计划类型<select v-model="form.triggerType"><option value="once">单次</option><option value="interval">固定间隔</option><option value="daily">每天</option><option value="weekly">每周</option><option value="cron">Cron</option></select></label><label v-if="form.triggerType==='once'">执行时间<input v-model="form.onceAt" type="datetime-local" required/></label><label v-if="form.triggerType==='interval'">间隔（分钟）<input v-model.number="form.intervalMinutes" type="number" min="1" max="525600"/></label><label v-if="['daily','weekly'].includes(form.triggerType)">时间<input v-model="form.time" type="time"/></label><label v-if="form.triggerType==='cron'" class="wide">Cron（分 时 日 月 星期）<input v-model="form.cron" placeholder="0 9 * * 1-5"/></label><fieldset v-if="form.triggerType==='weekly'" class="wide weekdays"><legend>星期</legend><label v-for="(label,index) in ['日','一','二','三','四','五','六']" :key="index"><input v-model="form.weekdays" type="checkbox" :value="index"/>周{{label}}</label></fieldset><label>时区<input v-model="form.timezone" required/></label><label v-if="form.targetType==='agent'">模型<input v-model="form.model" list="automation-models" required/><datalist id="automation-models"><option v-for="item in models" :key="item.id" :value="item.instanceId||item.id"></option></datalist></label><label v-if="form.targetType==='agent'">Agent 模式<select v-model="form.mode"><option value="coding">编码</option><option value="general">通用</option><option value="documents">文档</option></select></label><label v-if="form.targetType==='agent'">无人值守权限<select v-model="form.approvalMode"><option value="ask">安全：需确认操作直接拒绝</option><option value="auto">标准：允许项目策略内操作</option><option value="full">自主：允许更多自动操作</option><option value="unrestricted">完全控制：无需确认</option></select></label><label v-if="form.targetType==='agent'">最大步骤<input v-model.number="form.maxSteps" type="number" min="1" max="500"/></label><label>超时（分钟）<input v-model.number="form.timeoutMinutes" type="number" min="1" max="1440"/></label><label>失败重试次数<input v-model.number="form.retryMax" type="number" min="0" max="10"/></label><label>重试间隔（分钟）<input v-model.number="form.retryDelayMinutes" type="number" min="1" max="1440"/></label><label>系统通知<select v-model="form.notifyOn"><option value="failure">仅失败</option><option value="always">每次完成</option><option value="never">不通知</option></select></label><label v-if="form.targetType==='agent'" class="check"><input v-model="form.fastMode" type="checkbox"/>使用快速 Agent 模式</label></div>
     <footer><p>同一任务不会并发执行；错过的计划会在应用下次启动后触发。</p><button class="primary-button" :disabled="busy==='save'" type="submit">{{busy==='save'?'保存中…':'保存任务'}}</button></footer>
    </form>
    <div v-else class="history-panel"><header><div><span class="eyebrow">RUN HISTORY</span><h2>{{selected?'“'+selected.name+'”的运行历史':'全部运行历史'}}</h2></div><button v-if="historyTask||selected" class="text-button" @click="historyTask='';selectedId=''">查看全部</button></header><div v-if="!visibleRuns.length" class="automation-empty compact"><p>暂无运行记录</p></div><article v-for="run in visibleRuns" :key="run.id" class="run-card"><div><strong>{{run.taskName}}</strong><span class="run-state" :class="run.status">{{statusLabel(run.status)}}</span></div><p>计划 {{date(run.scheduledAt)}}<template v-if="run.startedAt"> · 开始 {{date(run.startedAt)}}</template><template v-if="run.retryCount"> · 已重试 {{run.retryCount}} 次</template></p><p v-if="run.summary" class="run-summary">{{run.summary}}</p><p v-if="run.error" class="run-error">{{run.error}}</p><small v-if="run.agentTaskId">Agent 运行：{{run.agentTaskId}}</small></article></div>
   </section>
  </div>
 </main>
</template>

<style scoped src="./studio-automation.css"></style>
