<script setup lang="ts">
import {DEEPSEEK_CONTEXT_TOKENS,isDeepSeek,deepseekModels} from '../electron/shared/local-ai-providers'
import {computed,reactive,ref,watch} from 'vue'
import AgentExtensions from './local-ai/AgentExtensions.vue'
import LocalAiAgent from './local-ai/LocalAiAgent.vue'
import {ChatDotRound,Search,FolderOpened,Connection,Setting,Plus,Close,Download,Refresh,CopyDocument,VideoPause,VideoPlay,Operation,Document,Cpu,ArrowRight,Check} from '@element-plus/icons-vue'
import LocalAiDeveloper from './local-ai/LocalAiDeveloper.vue'
import AgentToolManager from './local-ai/AgentToolManager.vue'
import ModelReadme from './local-ai/ModelReadme.vue'
import {useModelIcons} from './local-ai/useModelIcons'
import {useLocalAiStudio} from './local-ai/useLocalAiStudio'
import {useStudioLayout} from './local-ai/useStudioLayout'
import {LOCAL_AI_MAX_OUTPUT_TOKENS} from '../electron/shared/local-ai'
defineProps<{standalone?:boolean}>()
const studio=useLocalAiStudio()
const chat=reactive(studio)
watch(studio.tab,value=>{if(value==='chat')studio.tab.value='agent'})
const {modelsBusy,tab,ready,error,busy,drawer,parameters,data,settings,apiKey,hfToken,connection,connecting,remoteProfiles,input,model,systemPrompt,query,format,sort,searching,results,selected,filesBusy,fileFilter,ggufOnly,modelFilter,showMissing,enqueueBusy,sending,downloads,runtime,hardware,activeDownloads,totalSize,localModels,serverModels,statusText,online,bytes,count,percent,downloadLabel,fit,refreshModels,saveSettings,saveRemoteProfile,useRemoteProfile,deleteRemoteProfile,clearKey,connect,switchSource,selectRemoteApiFormat,usePreset,search,selectRepo,enqueue,downloadAction,importModels,removeModel,startModel,stopModel,chooseDirectory,copy,reveal,openLink,catalogSource,catalogUpdatedAt,catalogError,catalogLabel,details,detailsError,readme,readmeBusy,readmeError,loadReadme,selectedFileName,downloadChoices,selectedDownload,downloadSize,downloadParts,modelFormats,parameterLabel,dateLabel}=studio
const {studioRoot,narrow,compact,floatingInspector,detailsOpen,resizing,layoutStyle,layoutKey}=useStudioLayout(parameters,tab,drawer)
const {modelIcons,iconFailed}=useModelIcons(computed(()=>ready.value&&tab.value==='discover'?results.value.map(item=>item.author):[]))
const agentState=ref('')
const navigation=[{id:'agent',label:'工作台',icon:ChatDotRound},{id:'discover',label:'发现模型',icon:Search},{id:'models',label:'我的模型',icon:FolderOpened},{id:'server',label:'模型服务',icon:VideoPlay},{id:'tools',label:'工具',icon:Operation},{id:'settings',label:'设置',icon:Setting}] as const
const pageTitle=computed(()=>navigation.find(item=>item.id===tab.value)?.label||'本地 AI')
const memoryPercent=computed(()=>hardware.value?Math.round((1-hardware.value.freeMemory/hardware.value.totalMemory)*100):0)
const profileName=ref(''),profileId=ref(''),profileNameEdited=ref(false)
const remotePane=ref<'openai'|'anthropic'|'history'>('openai')
const suggestedProfileName=computed(()=>{
 let provider=settings.apiFormat==='anthropic'?'Anthropic':'OpenAI'
 if(isDeepSeek(settings.endpoint))provider='DeepSeek'
 else try{const url=new URL(settings.endpoint),host=url.hostname.replace(/^(api|www)\./i,'');provider=url.hostname==='127.0.0.1'||url.hostname==='localhost'?url.port==='1234'?'LM Studio':url.port==='11434'?'Ollama':url.port==='8080'?'llama.cpp':'本地兼容 API':host||provider}catch{}
 return `${provider}${settings.model.trim()?` · ${settings.model.trim()}`:''}`.slice(0,80)
})
const activeRemoteProfile=computed(()=>remoteProfiles.value.find(profile=>profile.apiFormat===settings.apiFormat&&profile.endpoint===settings.endpoint&&profile.model===settings.model))
watch(suggestedProfileName,name=>{if(!profileId.value&&!profileNameEdited.value)profileName.value=name},{immediate:true})
watch(activeRemoteProfile,profile=>{if(profile&&!profileId.value){profileId.value=profile.id;profileName.value=profile.name;profileNameEdited.value=true}},{immediate:true})
const serviceMode=ref<'local'|'remote'>('remote')
watch(()=>settings.source,source=>{serviceMode.value=source==='managed'?'local':'remote'},{immediate:true})
watch(()=>settings.apiFormat,format=>{if(remotePane.value!=='history')remotePane.value=format},{immediate:true})
function selectServiceMode(value:'local'|'remote'){serviceMode.value=value}
function selectRemotePane(value:'openai'|'anthropic'|'history'){remotePane.value=value;if(value!=='history')selectRemoteApiFormat(value)}
const selectedServiceOnline=computed(()=>serviceMode.value==='local'?runtime.value?.state==='running':settings.source==='external'&&connection.value?.ok===true)
const selectedServiceStatus=computed(()=>serviceMode.value==='local'?({stopped:'本地服务未启动',starting:'本地模型加载中',running:settings.source==='managed'?'本地服务使用中':'本地服务已启动',stopping:'本地服务停止中',error:'本地服务异常'}[runtime.value?.state||'stopped']):settings.source==='external'?(connection.value?.ok?'远程服务使用中':'远程服务未连接'):'远程服务未使用')
const viewedServiceActive=computed(()=>serviceMode.value==='local'?settings.source==='managed':settings.source==='external')
const canActivateViewedService=computed(()=>serviceMode.value==='remote'||runtime.value?.state==='running')
const viewedServiceState=computed(()=>!viewedServiceActive.value?(serviceMode.value==='local'&&runtime.value?.state!=='running'?'需要先启动本地模型':'当前未使用'):serviceMode.value==='local'&&runtime.value?.state!=='running'?'当前已选用 · 服务未启动':serviceMode.value==='remote'&&!connection.value?.ok?'当前已选用 · 尚未连接':'当前正在使用')
async function activateViewedService(){if(viewedServiceActive.value)return;if(serviceMode.value==='local')await switchSource('managed');else await saveRemoteConnection()}
async function saveRemoteConnection(){await saveProfile(true)}
const profileLabel=(profile:{name:string;endpoint:string})=>profile.name||new URL(profile.endpoint).host
function newProfile(){profileId.value='';profileNameEdited.value=false;profileName.value=suggestedProfileName.value}
async function deleteProfile(){if(!profileId.value)return;await deleteRemoteProfile(profileId.value);newProfile()}
async function selectRemoteProfile(event:Event){const id=(event.target as HTMLSelectElement).value,profile=remoteProfiles.value.find(item=>item.id===id);if(!profile)return;profileId.value=profile.id;profileName.value=profile.name;profileNameEdited.value=true;await useRemoteProfile(id)}
async function saveProfile(activate=false){
 const name=profileName.value.trim()||suggestedProfileName.value
 const editingId=profileId.value
 if(!await saveRemoteProfile({...(editingId?{id:editingId}:{}),name,apiFormat:settings.apiFormat,endpoint:settings.endpoint,model:settings.model,contextLength:settings.contextLength,...(apiKey.value?{apiKey:apiKey.value}:{})},false))return
 const saved=remoteProfiles.value.find(item=>item.id===editingId)||remoteProfiles.value.find(item=>item.name===name&&item.apiFormat===settings.apiFormat&&item.endpoint===settings.endpoint&&item.model===settings.model)
 if(saved){profileId.value=saved.id;profileName.value=saved.name;profileNameEdited.value=true}
 if(activate){if(settings.source==='external')await connect();else await switchSource('external')}
}
</script>

<template>
 <section ref="studioRoot" class="local-ai-studio" :class="{standalone,'agent-view':tab==='agent','narrow-layout':narrow,'compact-layout':compact,'floating-inspector':floatingInspector,'is-resizing':resizing}" :style="layoutStyle" :data-theme="settings.theme" @keydown="layoutKey">
  <nav class="activity-rail" aria-label="本地 AI 工作区">
   <div class="studio-mark" title="MyPlaneAgent Local AI"><span></span><span></span><span></span></div>
   <button v-for="item in navigation" :key="item.id" class="rail-button" :class="{active:tab===item.id}" :title="item.label" :aria-label="item.label" :aria-current="tab===item.id?'page':undefined" @click="tab=item.id"><component :is="item.icon"/><b v-if="item.id==='agent'&&['running','waiting'].includes(agentState)" class="rail-count">{{agentState==='waiting'?'!':'·'}}</b></button>
   <div class="rail-spacer"></div><button class="rail-button" :class="{active:drawer}" aria-label="下载队列" title="下载队列" @click="drawer=!drawer"><Download/><b v-if="activeDownloads.length" class="rail-count">{{activeDownloads.length}}</b></button>
  </nav>
  <div class="studio-main">
   <header class="studio-topbar"><div class="brand"><strong>AI 工作台</strong><span class="topbar-divider"></span><span>{{pageTitle}}</span></div><button class="connection-indicator" :class="{online}" @click="tab='server'"><i></i>{{statusText}}<ArrowRight/></button><span class="privacy-label">{{settings.source==='managed'?'本地服务 · 数据留在本机':'远程服务 · 请求发送至 API'}}</span></header>
   <div v-if="error" class="error-banner" role="alert"><span>{{error}}</span><button @click="error=''">关闭</button></div>
   <LocalAiAgent v-if="ready" v-show="tab==='agent'" :model="model" :models="serverModels" :online="online" :chat="chat" @state="agentState=$event"/>
   <div v-if="!ready" class="initial-loading"><div class="loading-orbit"></div><h3>{{error?'工作区暂时无法载入':'正在准备本地工作区'}}</h3><p>{{error?'请检查上方错误提示，修复后重新打开此窗口。':'读取本地模型、配置和会话记录'}}</p></div>

   <main v-else-if="tab==='discover'" class="discover-workspace catalog-workspace" :class="{'has-details':!!selected,'details-open':detailsOpen}">
    <button v-if="narrow&&detailsOpen&&selected" class="panel-backdrop" aria-label="关闭模型详情" @click="detailsOpen=false"></button>
    <section class="discovery-browser">
     <div class="discovery-controls">
      <header class="catalog-intro"><span class="eyebrow">MODEL DISCOVERY</span><h1>发现你的下一个模型</h1></header>
      <form class="discovery-search" @submit.prevent="search()"><Search/><input v-model="query" placeholder="在 Hugging Face 上搜索模型…" aria-label="搜索 Hugging Face 模型"/><button type="submit" class="icon-btn" :disabled="searching" aria-label="搜索模型"><ArrowRight/></button></form>
      <div class="catalog-quick-filters"><button :class="{active:!query}" @click="search('')">全部</button><button v-for="family in ['Qwen','Llama','DeepSeek','Gemma']" :key="family" :class="{active:query===family}" @click="search(family)">{{family}}</button></div>
      <div class="discovery-filters"><div class="segmented"><button :class="{active:format==='gguf'}" @click="format='gguf'">GGUF</button><button :class="{active:format==='all'}" @click="format='all'">所有格式</button></div><select v-model="sort" aria-label="模型排序"><option value="downloads">热门下载</option><option value="likes">最多喜欢</option><option value="lastModified">最近更新</option></select></div>
     </div>
     <div class="catalog-caption"><strong>{{catalogSource==='builtin'?'精选模型':query?'搜索结果':'热门模型'}} <span>{{results.length}}</span></strong><button class="icon-btn" :class="{spinning:searching}" :disabled="searching" aria-label="刷新模型目录" title="刷新模型目录" @click="search()"><Refresh/></button></div>
     <div class="catalog-source" aria-live="polite"><i :class="{live:catalogSource==='live'}"></i><span>{{searching?'正在更新，仍可浏览当前列表':catalogLabel}}{{!searching&&catalogUpdatedAt?' · '+dateLabel(catalogUpdatedAt):''}}</span></div>
     <div v-if="catalogError" class="catalog-warning" role="status"><p>{{catalogError}}</p><button class="text-button" :disabled="searching" @click="search()">重新连接</button><button class="text-button" @click="selectServiceMode('remote');tab='server'">远程服务设置</button></div>
     <div class="discovery-results" :aria-busy="searching">
      <div v-if="searching&&!results.length" class="search-skeleton"><div v-for="n in 5" :key="n"></div></div>
      <div v-else-if="!results.length" class="empty-panel"><Search/><h3>{{catalogError?'暂时无法取得搜索结果':'没有匹配的模型'}}</h3><p>{{catalogError?'连接恢复后重试，或先浏览内置精选模型。':'试试模型名称或作者，或切换到所有格式。'}}</p><button class="text-button" @click="search('')">浏览模型目录 <ArrowRight/></button></div>
      <div class="model-results"><button v-for="item in results" :key="item.id" class="discovery-card" :class="{selected:selected?.id===item.id}" :aria-pressed="selected?.id===item.id" @click="detailsOpen=true;selectRepo(item)">
       <div class="result-avatar" :class="{'avatar-qwen':item.author==='Qwen','avatar-community':item.author!=='Qwen','has-icon':!!modelIcons[item.author]}"><img v-if="modelIcons[item.author]" :src="modelIcons[item.author]" :alt="item.author+' 图标'" loading="lazy" decoding="async" @error="iconFailed(item.author)"/><span v-else>{{item.id.split('/').at(-1)?.slice(0,1).toUpperCase()}}</span></div>
       <div class="result-detail"><div class="catalog-model-title"><strong :title="item.id">{{item.id.split('/').at(-1)?.replace(/-GGUF$/i,'')}}</strong><span v-if="item.tags.includes('gguf')" class="catalog-format">GGUF</span></div><p class="catalog-description" :title="item.description">{{item.description}}</p><div class="result-meta"><span class="catalog-author" :title="item.author">{{item.author}}</span><template v-if="item.metricsKnown"><span><Download/>{{count(item.downloads)}}</span><span>{{count(item.likes)}} 喜欢</span></template><span v-else>精选</span><span v-if="item.parameterCount" class="catalog-params">{{parameterLabel(item.parameterCount)}}</span></div></div>
      </button></div>
     </div>
     <div class="catalog-library-footer"><Cpu/><span v-if="hardware">本机 {{bytes(hardware.totalMemory)}} 内存<small>运行需求随模型与上下文变化</small></span><span v-else>下载模型，留在本机</span></div>
    </section>
    <aside v-show="!narrow||selected&&detailsOpen" id="studio-details" class="model-details" :role="narrow?'dialog':undefined" :aria-modal="narrow?true:undefined" aria-label="模型详情">
     <template v-if="selected">
      <div class="detail-heading"><button v-if="narrow" class="text-button details-back" aria-label="返回搜索结果" @click="detailsOpen=false"><ArrowRight/>返回结果</button><span class="catalog-repo-heading" :title="selected.id">{{selected.id}}</span><button class="icon-btn" title="复制仓库名称" aria-label="复制仓库名称" @click="copy(selected.id)"><CopyDocument/></button><button class="icon-btn" title="在 Hugging Face 查看" aria-label="在 Hugging Face 查看" @click="openLink('https://huggingface.co/'+selected.id)"><ArrowRight/></button></div>
      <div class="catalog-detail-body">
       <div class="catalog-detail-stats"><span><Download/>{{selected.metricsKnown?count(selected.downloads):'待联网'}} 下载</span><span>{{selected.metricsKnown?count(selected.likes):'待联网'}} 喜欢</span><small>更新于 {{dateLabel(selected.lastModified)}}</small></div>
       <section class="catalog-model-summary"><div class="catalog-publisher">{{selected.author}} <span>{{selected.metricsKnown?'Hugging Face 仓库':'内置精选 · 非实时统计'}}</span></div><h2>{{selected.id.split('/').at(-1)?.replace(/-GGUF$/i,'')}}</h2><p>{{selected.description}}</p><dl class="catalog-specs"><div><dt>参数量</dt><dd>{{parameterLabel(selected.parameterCount)}}</dd></div><div><dt>架构</dt><dd>{{selected.architecture||'未公开'}}</dd></div><div><dt>格式</dt><dd><span v-for="kind in modelFormats.length?modelFormats:selected.tags.includes('gguf')?['GGUF']:[]" :key="kind" class="format-chip">{{kind}}</span><span v-if="!modelFormats.length&&!selected.tags.includes('gguf')">待读取</span></dd></div><div v-if="details?.contextLength"><dt>上下文</dt><dd>{{details.contextLength.toLocaleString()}} tokens</dd></div><div v-if="selected.license"><dt>许可</dt><dd>{{selected.license}}</dd></div></dl><div v-if="selected.capabilities.length" class="catalog-capabilities"><span>能力标签</span><b v-for="capability in selected.capabilities" :key="capability">{{capability}}</b></div></section>
       <section class="catalog-download-section"><div class="detail-file-head"><h3>下载选项</h3><label><input v-model="ggufOnly" type="checkbox"/>仅 GGUF</label></div><p v-if="details?.gated" class="catalog-warning">此仓库受访问限制。请在 Hugging Face 接受许可，并在设置中填写有权限的 Token。</p>
        <div class="catalog-download-card"><label class="compact-search"><Search/><input v-model="fileFilter" placeholder="筛选量化版本或文件名" aria-label="筛选模型文件"/></label><p v-if="filesBusy" class="quiet">正在读取量化版本、大小与校验信息…</p><div v-else-if="detailsError" class="catalog-inline-error" role="status"><p>{{detailsError}}</p><button class="text-button" @click="selectRepo(selected)"><Refresh/>重试加载文件</button></div><p v-else-if="!downloadChoices.length" class="quiet">没有匹配的文件，试试清空筛选或取消“仅 GGUF”。</p>
         <template v-if="selectedDownload"><label class="catalog-quant-label" for="catalog-quantization">选择文件 / 量化版本 <span>{{downloadChoices.length}} 个选项</span></label><select id="catalog-quantization" class="catalog-quant-select" aria-label="选择量化版本" :value="selectedDownload.file" @change="selectedFileName=($event.target as HTMLSelectElement).value"><option v-for="file in downloadChoices" :key="file.file" :value="file.file">{{file.quantization||file.format}} · {{file.file}} · {{file.size?bytes(file.size):'大小未知'}}</option></select><p class="catalog-selected-file">{{selectedDownload.file}}</p><div class="catalog-download-bottom"><div class="catalog-fit"><span class="format-chip">{{selectedDownload.quantization||selectedDownload.format}}</span><small>{{selectedDownload.format==='GGUF'?fit(downloadSize):'需要支持此格式的外部运行时'}}</small><small v-if="downloadParts.length>1">包含 {{downloadParts.length}} 个分片，总计 {{downloadSize?bytes(downloadSize):'大小未知'}}</small><small v-if="selectedDownload.sha256">下载后校验 SHA-256</small></div><button class="download-file" :disabled="!!enqueueBusy" @click="enqueue(selectedDownload)"><Download/>{{enqueueBusy?'加入队列中':'下载'}}<strong>{{downloadSize?bytes(downloadSize):'大小未知'}}</strong></button></div></template>
        </div><p class="file-footnote">分片 GGUF 自动下载所有分片。内存提示仅按文件体积粗估，不代表显存检测或运行保证；视觉模型可能还需要配套投影文件。</p>
       </section>
       <section class="catalog-readme"><header><h3>README</h3><button class="text-button" @click="openLink('https://huggingface.co/'+selected.id)">查看原文 <ArrowRight/></button></header><div v-if="readmeBusy" class="catalog-readme-loading"><div class="loading-orbit"></div><p>正在读取模型卡…</p></div><div v-else-if="readmeError" class="catalog-inline-error"><p>{{readmeError}}</p><button class="text-button" @click="loadReadme"><Refresh/>重试读取</button></div><div v-else-if="readme" class="catalog-readme-content"><ModelReadme :text="readme" :repo-id="selected.id" :revision="details?.revision"/></div><div v-else class="catalog-readme-empty"><Document/><p>{{filesBusy?'文件信息加载后显示模型卡。':detailsError?'联网后可查看模型作者的完整介绍。':'仓库未提供 README，可前往 Hugging Face 查看详情。'}}</p></div></section>
      </div>
     </template>
     <div v-else class="details-placeholder"><Document/><h3>选择模型，探索细节</h3><p>这里会显示模型介绍、量化版本、下载选项与 README。</p></div>
    </aside>
   </main>

   <main v-else-if="tab==='models'" class="scroll-page"><header class="page-intro with-actions"><div><span class="eyebrow">YOUR MODEL LIBRARY</span><h1>我的模型</h1><p>下载、导入、加载。把适合你的模型留在本机。</p></div><div class="button-row"><button class="secondary-button" :disabled="!!busy" @click="importModels"><Plus/>导入 GGUF</button><button class="primary-button" @click="tab='discover'"><Search/>发现模型</button></div></header><div class="library-stats"><article><FolderOpened/><div><strong>{{data?.models.length||0}}</strong><span>模型文件</span></div></article><article><Document/><div><strong>{{bytes(totalSize)}}</strong><span>本地文件总大小</span></div></article><article><Cpu/><div><strong>{{runtime?.state==='running'?'1':'0'}}</strong><span>MyPlaneAgent 已加载</span></div></article></div><div class="library-toolbar"><label class="compact-search"><Search/><input v-model="modelFilter" placeholder="搜索本地模型" aria-label="搜索本地模型"/></label><label class="checkbox-label"><input v-model="showMissing" type="checkbox"/>显示缺失文件</label><button class="icon-btn" :disabled="modelsBusy||!ready" aria-label="刷新模型库" @click="refreshModels().catch(e=>error=String(e))"><Refresh/></button></div>
    <p v-if="modelsBusy" role="status" aria-live="polite">正在扫描已保存的模型目录，加载模型列表…</p><div v-if="!modelsBusy&&!localModels.length" class="empty-panel large"><FolderOpened/><h2>给你的工作区添一个模型</h2><p>打开此页面会扫描设置中保存的下载目录。也可从 Hugging Face 下载 GGUF，或导入已有模型。<br/>导入会保留原文件位置，不会复制大型模型文件。</p><button class="primary-button" @click="tab='discover'">浏览模型</button></div><div v-else-if="localModels.length" class="library-table" :aria-busy="modelsBusy"><div class="library-table-head"><span>模型 / 文件</span><span>大小</span><span>状态</span><span>操作</span></div><article v-for="item in localModels" :key="item.id" class="library-row"><div class="library-model"><span class="library-icon"><Cpu/></span><div><strong :title="item.file">{{item.file}}</strong><small>{{item.repoId}} · {{item.quantization||item.format}}</small><small class="model-path" :title="item.localPath">{{item.localPath}}</small></div></div><span class="model-size">{{bytes(item.size)}}</span><span class="state-tag" :class="{loaded:runtime?.modelId===item.id&&runtime.state==='running',missing:!item.exists}">{{!item.exists?'文件缺失':runtime?.modelId===item.id&&runtime.state==='running'?'已加载':runtime?.modelId===item.id&&runtime.state==='starting'?'加载中':'在硬盘中'}}</span><div class="library-actions"><button v-if="runtime?.modelId===item.id&&['starting','running'].includes(runtime.state)" class="secondary-button" :disabled="!!busy||sending" @click="stopModel">卸载</button><button v-else class="secondary-button" :disabled="!!busy||!item.exists||item.format!=='GGUF'||sending||['running','starting','stopping'].includes(runtime?.state||'')" @click="startModel(item)"><VideoPlay/>加载</button><button class="icon-btn" aria-label="在文件夹中显示" :disabled="!item.exists" @click="reveal(item)"><FolderOpened/></button><details class="model-menu"><summary title="更多操作">···</summary><div><button @click="removeModel(item)">移除记录，保留文件</button><button class="danger-text" @click="removeModel(item,true)">删除磁盘文件</button></div></details></div></article></div><div class="page-note"><span class="format-chip">GGUF</span><p>本机托管运行使用 llama.cpp。Safetensors / MLX 等格式需连接相应外部服务。分片 GGUF 请加载第一个分片；切换模型前先卸载当前模型。</p></div>
   </main>

   <main v-else-if="tab==='server'" class="service-workspace">
    <aside class="service-secondary-nav"><header><span class="eyebrow">MODEL SERVICE</span><h2>模型服务</h2><p>查看配置并选择实际使用的服务</p></header><nav aria-label="模型服务二级菜单"><button :class="{active:serviceMode==='local'}" :aria-current="serviceMode==='local'?'page':undefined" @click="selectServiceMode('local')"><Cpu/><span><strong>本地服务 <em v-if="settings.source==='managed'">使用中</em></strong><small>llama.cpp 与本机模型</small></span><ArrowRight/></button><button :class="{active:serviceMode==='remote'}" :aria-current="serviceMode==='remote'?'page':undefined" @click="selectServiceMode('remote')"><Connection/><span><strong>远程服务 <em v-if="settings.source==='external'">使用中</em></strong><small>云端及兼容 API</small></span><ArrowRight/></button></nav><footer><span class="service-live-pill" :class="{online}"><i></i>当前使用：{{settings.source==='managed'?'本地服务':'远程服务'}}</span></footer></aside>
    <section class="service-workspace-content"><header class="service-workspace-header"><div><span class="eyebrow">{{serviceMode==='local'?'LOCAL SERVICE':'REMOTE SERVICE'}}</span><h1>{{serviceMode==='local'?'本地服务':'远程服务'}}</h1><p>{{serviceMode==='local'?'配置运行时、加载本机模型并管理兼容 API。':'选择 API 格式并保存连接。'}}</p></div><aside class="service-use-control" :class="{active:viewedServiceActive&&selectedServiceOnline}"><span><i></i>{{viewedServiceState}}</span><button v-if="!viewedServiceActive" class="primary-button" :disabled="!canActivateViewedService||!!busy||connecting" @click="activateViewedService"><VideoPlay/>{{serviceMode==='local'?'切换到本地服务':'保存并切换到远程服务'}}</button></aside></header>
     <section v-if="serviceMode==='local'" class="service-local-panel"><LocalAiDeveloper service-mode="managed" :settings="settings" :runtime="runtime" :models="data?.models||[]" :connection="connection" :connecting="connecting" @settings="Object.assign(settings,$event)" @runtime="data&&(data.runtime=$event)" @connect="connect()" @import-models="importModels" @discover="tab='discover'" @settings-page="selectServiceMode('remote')"/></section>
    <section v-else class="service-remote-panel"><div class="service-remote-grid">
     <section class="content-card remote-connection-card">
      <header><span class="remote-card-icon"><Connection/></span><div><h3>{{remotePane==='history'?'配置历史':'连接配置'}}</h3><p class="card-subtitle">{{remotePane==='history'?'切换、保存和管理常用连接。':'填写地址、模型和密钥。'}}</p></div><span v-if="remotePane!=='history'" class="remote-inline-status" :class="{online:connection?.ok}"><i></i>{{connection?.ok?'已连接':'未连接'}}</span></header>
      <div class="remote-api-formats" role="radiogroup" aria-label="远程 API 格式">
       <button :class="{active:remotePane==='openai'}" :aria-checked="remotePane==='openai'" role="radio" @click="selectRemotePane('openai')"><b>O</b><span><strong>OpenAI 格式</strong><small>/chat/completions</small></span><Check/></button>
       <button :class="{active:remotePane==='anthropic'}" :aria-checked="remotePane==='anthropic'" role="radio" @click="selectRemotePane('anthropic')"><b>A</b><span><strong>Anthropic 格式</strong><small>/messages</small></span><Check/></button>
       <button :class="{active:remotePane==='history'}" :aria-checked="remotePane==='history'" role="radio" @click="selectRemotePane('history')"><b><Setting/></b><span><strong>配置历史</strong><small>{{remoteProfiles.length}} 条已保存配置</small></span><Check/></button>
      </div>
      <div v-if="remotePane==='history'" class="remote-history-pane"><div v-if="remoteProfiles.length" class="remote-profile-picker"><label><span>已保存配置</span><select :value="profileId||activeRemoteProfile?.id||''" :disabled="!!busy||connecting" aria-label="选择远程服务配置" @change="selectRemoteProfile"><option value="" disabled>选择一个远程配置</option><option v-for="profile in remoteProfiles" :key="profile.id" :value="profile.id">[{{profile.apiFormat==='anthropic'?'Anthropic':'OpenAI'}}] {{profileLabel(profile)}} · {{profile.model||'未指定模型'}} · {{profile.contextLength.toLocaleString()}} tokens</option></select></label><button class="icon-btn danger-icon" :disabled="!profileId" title="删除当前配置" aria-label="删除当前配置" @click="deleteProfile"><Close/></button></div><p v-else class="quiet">还没有保存的配置，可在下方填写并保存。</p>
       <div class="remote-history-detail"><div class="remote-history-detail-head"><span>{{profileId?'正在编辑':'当前连接'}}</span><strong>{{profileName||profileId||'未命名配置'}}</strong><em>{{settings.apiFormat==='anthropic'?'Anthropic 格式':'OpenAI 格式'}}</em></div><div class="remote-field-grid"><label class="field">API 格式<select v-model="settings.apiFormat"><option value="openai">OpenAI 格式</option><option value="anthropic">Anthropic 格式</option></select></label><label class="field">默认模型 ID<input v-model="settings.model" list="history-settings-models" :placeholder="settings.apiFormat==='anthropic'?'例如 claude-sonnet-4-6':'服务返回的模型 ID'"/><datalist id="history-settings-models"><option v-for="id in (settings.apiFormat==='openai'&&isDeepSeek(settings.endpoint)?deepseekModels:[])" :key="id" :value="id"></option><option v-for="item in serverModels" :key="item.id" :value="item.instanceId||item.id"></option></datalist></label><label class="field remote-endpoint-field">API 服务地址<input v-model="settings.endpoint" :placeholder="settings.apiFormat==='anthropic'?'https://api.anthropic.com/v1':'https://api.example.com/v1'" type="url"/></label><label class="field">Agent 上下文预算<input v-model.number="settings.contextLength" type="number" min="512" :max="settings.apiFormat==='openai'&&isDeepSeek(settings.endpoint)?DEEPSEEK_CONTEXT_TOKENS:131072" step="512"/></label><label class="field">{{settings.apiFormat==='anthropic'?'Anthropic API Key':'API Key'}}<input v-model="apiKey" type="password" autocomplete="new-password" :placeholder="settings.hasApiKey?'已安全保存，留空不修改':'服务要求鉴权时填写'"/></label></div><div class="remote-security-note"><Check/><span>{{settings.hasApiKey?'密钥已加密保存在本机':'尚未保存密钥'}}</span><button v-if="settings.hasApiKey" class="text-button danger-text" :disabled="!!busy" @click="clearKey('api')">移除</button></div></div>
       <div class="profile-save-row"><input v-model="profileName" maxlength="80" :placeholder="'自动生成：'+suggestedProfileName" aria-label="远程配置名称" @input="profileNameEdited=true"/><button class="primary-button" :disabled="!!busy||sending||connecting" @click="saveProfile()"><Check/>{{connecting?'正在测试…':settings.source==='external'?(profileId?'更新并测试':'保存并测试'):(profileId?'更新配置':'保存配置')}}</button><button v-if="profileId" class="text-button" @click="newProfile">另存为</button></div><p v-if="connection&&settings.source==='external'" class="connection-result" :class="{success:connection.ok}">{{connection.ok?'连接成功 · '+connection.models.length+' 个模型':connection.error}}</p></div>
      <template v-else><div v-if="settings.apiFormat==='openai'" class="remote-preset-group"><span>快捷填充</span><div class="remote-quick-presets"><button @click="usePreset('deepseek')">DeepSeek</button><button @click="usePreset('lmstudio')">LM Studio</button><button @click="usePreset('ollama')">Ollama</button><button @click="usePreset('llamacpp')">llama.cpp</button></div></div>
       <div class="remote-field-grid"><label class="field">配置名称<input v-model="profileName" maxlength="80" :placeholder="'自动生成：'+suggestedProfileName" @input="profileNameEdited=true"/></label><label class="field remote-endpoint-field">API 服务地址<input v-model="settings.endpoint" :placeholder="settings.apiFormat==='anthropic'?'https://api.anthropic.com/v1':'https://api.example.com/v1'" type="url"/></label><label class="field">默认模型 ID<input v-model="settings.model" list="settings-models" :placeholder="settings.apiFormat==='anthropic'?'例如 claude-sonnet-4-6':'服务返回的模型 ID'"/><datalist id="settings-models"><option v-for="id in (settings.apiFormat==='openai'&&isDeepSeek(settings.endpoint)?deepseekModels:[])" :key="id" :value="id"></option><option v-for="item in serverModels" :key="item.id" :value="item.instanceId||item.id"></option></datalist></label><label class="field">Agent 上下文预算<input v-model.number="settings.contextLength" type="number" min="512" :max="settings.apiFormat==='openai'&&isDeepSeek(settings.endpoint)?DEEPSEEK_CONTEXT_TOKENS:131072" step="512"/></label><label class="field remote-key-field">{{settings.apiFormat==='anthropic'?'Anthropic API Key':'API Key'}}<input v-model="apiKey" type="password" autocomplete="new-password" :placeholder="settings.hasApiKey?'已安全保存，留空不修改':'服务要求鉴权时填写'"/></label></div>
       <div class="remote-security-note"><Check/><span>密钥已加密保存在本机</span><button v-if="settings.hasApiKey" class="text-button danger-text" :disabled="!!busy" @click="clearKey('api')">移除</button></div>
       <div class="remote-connect-actions"><button class="primary-button remote-connect-button" :disabled="!!busy||sending||connecting" @click="saveRemoteConnection"><VideoPlay/>{{connecting?'正在测试…':settings.source==='external'?(profileId?'更新并测试':'保存并测试'):(profileId?'更新并切换使用':'保存并切换使用')}}</button><button v-if="profileId" class="secondary-button" :disabled="!!busy||sending" @click="saveProfile()"><Check/>更新“{{profileName}}”</button><button v-if="profileId" class="text-button" @click="newProfile">另存为</button><p v-if="connection&&settings.source==='external'" class="connection-result" :class="{success:connection.ok}">{{connection.ok?'连接成功 · '+connection.models.length+' 个模型':connection.error}}</p></div></template>
     </section>
     </div></section>
    </section>
   </main>
   <AgentToolManager v-else-if="tab==='tools'"/>

   <main v-else-if="tab==='settings'" class="scroll-page settings-page"><header class="page-intro with-actions"><div><span class="eyebrow">PREFERENCES</span><h1>应用设置</h1><p>管理模型存储、界面外观和新会话默认值。服务连接请前往“模型服务”。</p></div><button class="primary-button" :disabled="!!busy||sending" @click="saveSettings()"><Check/>{{busy==='save'?'保存中':'保存设置'}}</button></header><div class="settings-grid">
    <section class="content-card"><header><h3>模型存储与 Hugging Face</h3><FolderOpened/></header><label class="field">下载目录<div class="path-field"><input v-model="settings.downloadDirectory" placeholder="选择模型保存目录"/><button class="icon-btn" :disabled="!!busy" aria-label="选择下载目录" @click="chooseDirectory"><FolderOpened/></button></div></label><p class="quiet">修改目录只影响新任务；现有模型和未完成下载仍使用原位置。</p><label class="field">Hugging Face Token<input v-model="hfToken" type="password" autocomplete="new-password" :placeholder="settings.hasHfToken?'已安全保存，留空不修改':'公开模型通常不需要 Token'"/></label><button v-if="settings.hasHfToken" class="text-button danger-text" :disabled="!!busy" @click="clearKey('hf')">移除已保存的 Token</button><div class="settings-tip"><Check/><p>密钥使用操作系统安全存储加密；下载可暂停、恢复，关闭应用后会保留进度。</p></div></section>
    <section class="content-card"><header><h3>工作区默认值</h3><Operation/></header><label class="field">界面外观<select v-model="settings.theme"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label><label class="field">新会话系统提示词<textarea v-model="settings.systemPrompt" rows="4" maxlength="12000" placeholder="例如：请使用中文，回答简洁，并给出必要的示例。"></textarea></label><div class="field-pair"><label class="field">Temperature<input v-model.number="settings.temperature" type="number" min="0" max="2" step="0.05"/></label><label class="field">最大输出 tokens<input v-model.number="settings.maxTokens" type="number" min="128" :max="LOCAL_AI_MAX_OUTPUT_TOKENS" step="128"/></label></div><p class="quiet">DeepSeek 推荐默认 65,536；快速 Agent 单轮使用 8,192。深度 Agent 与聊天使用这里的完整预算，且不超过有效上下文的一半。</p></section>
   </div><AgentExtensions/></main>
   <footer class="status-bar"><div><span class="status-dot" :class="{online}"></span><span>{{settings.source==='managed'?'本地 llama.cpp':'远程 API'}}</span><span class="footer-model">{{model||'未选择模型'}}</span></div><div><span v-if="hardware">RAM {{bytes(hardware.totalMemory-hardware.freeMemory)}} / {{bytes(hardware.totalMemory)}}</span><button @click="drawer=!drawer"><Download/>{{activeDownloads.length?activeDownloads.length+' 个下载任务':'下载队列'}}<span v-if="downloads.length" class="count-badge">{{downloads.length}}</span></button></div></footer>
  </div>
  <button v-if="drawer" class="download-backdrop" aria-label="关闭下载队列遮罩" @click="drawer=false"></button>
  <aside v-if="drawer" id="studio-downloads" class="downloads-drawer" role="dialog" aria-modal="true" aria-label="下载队列"><header><div><Download/><h3>下载队列</h3><span class="count-badge">{{downloads.length}}</span></div><button class="icon-btn" aria-label="关闭下载队列" @click="drawer=false"><Close/></button></header><p class="drawer-note">顺序下载 · 支持断点续传 · 下载完成后自动加入模型库</p><div class="download-items"><div v-if="!downloads.length" class="empty-panel"><Download/><h3>还没有下载任务</h3><button class="text-button" @click="tab='discover';drawer=false">去发现模型 <ArrowRight/></button></div><article v-for="item in [...downloads].reverse()" :key="item.id" class="download-item"><div class="download-item-head"><span class="format-chip">{{item.file.split('.').at(-1)?.toUpperCase()}}</span><span class="download-state" :class="item.status">{{downloadLabel(item.status)}}</span></div><strong :title="item.file">{{item.file}}</strong><small>{{item.repoId}}</small><div class="progress-track" :class="{indeterminate:item.status==='verifying'||!item.total&&item.status==='downloading'}"><span :style="{width:percent(item)+'%'}"></span></div><div class="download-progress-label"><span>{{bytes(item.received)}} / {{item.total?bytes(item.total):'未知大小'}}</span><span v-if="item.status==='downloading'">{{bytes(item.speed)}}/s · {{percent(item)}}%</span><span v-else-if="item.status==='completed'">{{item.sha256?'SHA-256 已校验':'已完成'}}</span></div><p v-if="item.error" class="download-error">{{item.error}}</p><div class="download-actions"><button v-if="['downloading','queued'].includes(item.status)" class="text-button" @click="downloadAction(item,'pause')"><VideoPause/>暂停</button><button v-if="['paused','failed'].includes(item.status)" class="text-button" @click="downloadAction(item,'resume')"><VideoPlay/>{{item.status==='failed'?'重试':'继续'}}</button><button v-if="!['completed','cancelled'].includes(item.status)" class="text-button" @click="downloadAction(item,'cancel')"><Close/>取消</button><button v-if="['completed','cancelled','failed'].includes(item.status)" class="text-button" @click="downloadAction(item,'remove')">清除记录</button><button v-if="item.status==='completed'" class="text-button" @click="tab='models';drawer=false">查看模型 <ArrowRight/></button></div></article></div></aside>
 </section>
</template>

<style scoped src="./local-ai/studio-layout.css"></style>
<style scoped src="./local-ai/studio-discovery.css"></style>

<style scoped src="./local-ai/studio-workbench.css"></style>
